#!/bin/bash
 printf "\e[1m Initializing..."
docker exec bioportal-api bash -c "cd /srv/ncbo/ncbo_cron && bundle install" &> /dev/null
docker exec bioportal-api bash -c "mkdir -p /srv/bioportal/reports/ && touch /srv/bioportal/reports/ontologies_reports.json || exit" &> /dev/null
printf "\e[32m [OK]\e[0m"
