#!/bin/bash


pwd=`pwd`
pushd `dirname $pwd`

rm $pwd/data/submit/mappings.ttl $pwd/data/submit/labels.ttl

echo "Processing ontologies..."
for ONTFILE in $(ls -1 $pwd/data/submit/*.ttl); do
	ACRONYM=$(basename $ONTFILE | cut -d'.' -f1)
	echo -e "\n\t$ACRONYM :Creating acronym"
	
	curl -X POST -H "Content-Type: application/json" -d "{ \"acronym\": \"$ACRONYM\", \"name\": \"$ACRONYM\", \"administeredBy\": [ ] }"  http://localhost:8080/ontologies 

	echo -e "\n\t$ACRONYM : Submitting ontology file..."	

	curl -X POST -H "Content-Type: application/json" -d "{ \"hasOntologyLanguage\": \"OWL\", \"uploadFilePath\": \"/srv/submit/$ACRONYM.ttl\", \"contact\": [{\"name\": \"Admin\", \"email\": \"admin@god.fr\"}],\"released\": \"2015-09-06\"}"  http://localhost:8080/ontologies/$ACRONYM/submissions	

	echo "curl -X POST -H 'Content-Type: application/json' -d { \"hasOntologyLanguage\": \"OWL\", \"uploadFilePath\": \"/srv/submit/$ACRONYM.ttl\", \"contact\": [{\"name\": \"Admin\", \"email\": \"admin@god.fr\"}],\"released\": \"2015-09-06\"}  http://localhost:8080/ontologies/$ACRONYM/submission" 


done

for ONTFILE in $(ls -1 $pwd/data/submit/*.owl); do
	ACRONYM=$(basename $ONTFILE | cut -d'.' -f1)
	echo -e "\n\t$ACRONYM :Creating acronym..."
	
	curl -X POST -H "Content-Type: application/json" -d "{ \"acronym\": \"$ACRONYM\", \"name\": \"$ACRONYM\", \"administeredBy\": [ ] }"  http://localhost:8080/ontologies 

	
	echo -e "\n\t$ACRONYM : Submitting ontology file..."
	

	curl -X POST -H "Content-Type: application/json" -d "{ \"hasOntologyLanguage\": \"OWL\", \"uploadFilePath\": \"/srv/submit/$ACRONYM.owl\", \"contact\": [{\"name\": \"Admin\", \"email\": \"admin@god.fr\"}],\"released\": \"2015-09-06\"}"  http://localhost:8080/ontologies/$ACRONYM/submissions	

done

for ONTFILE in $(ls -1 $pwd/data/submit/*.skos); do
	ACRONYM=$(basename $ONTFILE | cut -d'.' -f1)
	echo -e "\n\t$ACRONYM :Creating acronym..."
	
	curl -X POST -H "Content-Type: application/json" -d "{ \"acronym\": \"$ACRONYM\", \"name\": \"$ACRONYM\", \"administeredBy\": [ ] }"  http://localhost:8080/ontologies 

	echo -e "\n\t$ACRONYM : Submitting ontology file..."
	

	curl -X POST -H "Content-Type: application/json" -d "{ \"hasOntologyLanguage\": \"SKOS\", \"uploadFilePath\": \"/srv/submit/$ACRONYM.skos\", \"contact\": [{\"name\": \"Admin\", \"email\": \"admin@god.fr\"}],\"released\": \"2015-09-06\"}"  http://localhost:8080/ontologies/$ACRONYM/submissions	

done



printf "The ontologies have been submitted, the queue will start processing within a minute... The full indexing process may take between mitues and hours depending on the number of ontologies and their size.\n"

printf "I will show you the scheduler logs (tail -f data/ncbo_logs/scheduler.log)\n Please keep the logs open until the process is finishsed. \n \e[92m You will see: \e[1m 'Finished ontology process queue check' \n \e[1m"

sleep 15

tail -f $pwd/data/ncbo_logs/scheduler.log;

popd
