#!/bin/bash

pushd `dirname $0`
./init-ncbo-cron
echo "Re-generating cache..."
docker exec bioportal-api bash -c "cd /srv/ncbo/ncbo_cron && echo 'yes' | ruby -EUTF-8 ./bin/ncbo_ontology_annotate_generate_cache -a -d" 2>/dev/null
popd

