#!/bin/bash

pushd `dirname $0`
./init-ncbo-cron
printf "\e[1m Re-generating dictionary... \e[0m \n"
docker exec  bioportal-api bash -c "cd /srv/ncbo/ncbo_cron/ && echo 'yes' | ruby -EUTF-8 ./bin/ncbo_ontology_annotate_generate_dictionary -l logs/dictionary-gen.log" 2>/dev/null

echo `pwd`

java -jar Lemmatizer.jar ../data/mgrep/dictionary.txt ../data/mgrep/dictionary-lem.txt false
sudo cp ../data/mgrep/dictionary.dic ../data/unitex/

docker exec bioportal-unitex bash -c "cd /srv/unitex/ && ./unitex-core/bin/UnitexToolLogger Compress /srv/unitex/recognizer/data/French/Dela/dictionary.dic -o /srv/unitex/recognizer/data/French/Dela/dictionary.bin"

docker-compose restart bioportal-mgrep
popd
