#!/bin/bash

#echo "Starting Nginx..."
#/usr/sbin/nginx &
rm -rf /srv/ncbo/ontologies_api/log
echo "Starting unicorn..."
/srv/ncbo/unicorn 
echo "Starting NCBO Cron..."
/srv/ncbo/ncbo_cron_init

sleep 20

sleep infinity
