#!/bin/sh

prog=unicorn
APP_ROOT=/srv/ncbo/ontologies_api
ENVIRONMENT=production
UNICORN_CONF=$APP_ROOT/config/unicorn.rb
lockfile=/var/run/unicorn/unicorn.lock
pidfile=/var/run/unicorn/unicorn.pid
SLEEPMSEC=100000
RETVAL=0
BUNDLE_PATH=/usr/local/bin/

cd $APP_ROOT && $BUNDLE_PATH/bundle exec unicorn -c $UNICORN_CONF -E $ENVIRONMENT -D

